name: Deploy To On-premise

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: 🔧 Build & Push Docker Image to Docker Hub
    # ✅ 기존처럼 GitHub-hosted runner 유지
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Github Repository 파일 불러오기
        uses: actions/checkout@v4

      - name: ☕ JDK 21버전 설치
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: 🧪 테스트 및 빌드하기 (현재 설정대로 test 제외)
        run: |
          chmod +x ./gradlew
          ./gradlew clean build -x test

      - name: 🐳 Docker Hub 로그인
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # ✅ 기존 태그 정책 유지: IMAGE_NAME을 태그로 사용
      - name: 🐳 Docker 이미지 생성
        run: docker build -t ${{ secrets.IMAGE_NAME }} .

      - name: 🏷️ Docker 이미지에 Tag 붙이기
        run: docker tag ${{ secrets.IMAGE_NAME }} ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.REPOSITORY_NAME }}:${{ secrets.IMAGE_NAME }}

      - name: 🚀 Docker Hub에 Push
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.REPOSITORY_NAME }}:${{ secrets.IMAGE_NAME }}

  deploy-to-on-premise:
    name: 🚀 Deploy To On-premise
    # ✅ 배포만 self-hosted runner에서 실행
    runs-on: self-hosted # 추후 label부여해서 특정 runner에서만 실행되도록 수정
    needs: build-and-push

    steps:
      - name: 🐳 Docker Hub 로그인
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 🧹 Stop & Remove existing container
        run: |
          docker stop ${{ secrets.IMAGE_NAME }} || true
          docker rm ${{ secrets.IMAGE_NAME }} || true

      - name: 📥 Pull image from Docker Hub
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.REPOSITORY_NAME }}:${{ secrets.IMAGE_NAME }}

      - name: 🚀 Run container
        run: |
          docker run -d --name ${{ secrets.IMAGE_NAME }} -P \
            --network ${{ secrets.DOCKER_NETWORK_NAME }} \
            -e DB_HOST="${{secrets.DB_HOST}}" \
            -e APP_HOST="${{secrets.APP_HOST}}" \
            -e S3_BUCKET="${{ secrets.S3_BUCKET }}" \
            -e S3_ACCESS_KEY="${{ secrets.S3_ACCESS_KEY }}" \
            -e S3_SECRET_KEY="${{ secrets.S3_SECRET_KEY }}" \
            -e S3_REGION="${{ secrets.S3_REGION }}" \
            -e FILE_BASE_URL="${{ secrets.FILE_BASE_URL }}" \
            -e DB_URL="${{ secrets.DB_URL }}" \
            -e DB_USERNAME="${{ secrets.DB_USERNAME }}" \
            -e DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
            -e JWT_SECRET="${{ secrets.JWT_SECRET }}" \
            -e EUREKA_DEFAULTZONE="${{ secrets.EUREKA_DEFAULTZONE }}" \
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.REPOSITORY_NAME }}:${{ secrets.IMAGE_NAME }}
